services:
  prometheus:
    image: ubuntu/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - docker-net
    volumes:
      - ./prometheus:/etc/prometheus
    depends_on: 
      - node-exporter
      - postgres

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - docker-net
    depends_on:
      - prometheus
      - influxdb
    volumes:
      #- ./grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports: 
      - 9100:9100
    networks:
      - docker-net

  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUX_DB=db0
      - INFLUX_ADMIN_USER=admin
      - INFLUX_ADMIN_PASSWORD=admin
      #- DOCKER_INFLUXDB_INIT_MODE=setup
      #- DOCKER_INFLUXDB_INIT_USERNAME=admin
      #- DOCKER_INFLUXDB_INIT_PASSWORD=admin
      #- DOCKER_INFLUXDB_INIT_ORG=BellIntegrator
      #- DOCKER_INFLUXDB_INIT_BUCKET=tmpbucket
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    networks:
      - docker-net

  postgres-exporter:
    #image: bitnami/postgres-exporter
    image: wrouesnel/postgres_exporter
    container_name: postgres-exporter
    ports:
      - 9187:9187
    networks:
      - docker-net
    depends_on:
      - postgres
    environment:
      - DATA_SOURCE_URI=postgres:5432/greybaca?sslmode=disable
      - DATA_SOURCE_USER=greybaca
      - DATA_SOURCE_PASS=123456

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: "greybaca"
      POSTGRES_USER: "greybaca"
      POSTGRES_PASSWORD: "123456"
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - ./postgres_init/:/docker-entrypoint-initdb.d/
    networks:
      - docker-net
    ports:
      - 5432:5432

networks:
  docker-net:
    name: docker-net
